memodir = "${HOME}/.config/memo/_posts"
editor = "vim"
column = 50
selectcmd = "peco"
grepcmd = "ag ${PATTERN} ${FILES}"
assetsdir = "${HOME}/.config/memo/assets"
pluginsdir = "${HOME}/.config/memo/plugins"
templatedirfile = "${HOME}/.config/memo/templates/dir.html"
templatebodyfile = "${HOME}/.config/memo/templates/body.html"
